version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "java-hello1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1avr0ylgvc8ng"
s3_prefix = "java-hello1"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
